### ISSUE TITLE
FFT Extension example fails to run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tigerneil/aparapi#153]
```
What steps will reproduce the problem?
1. Checkout APARAPI
2. run ant build
3. cd samples/extension
4. run fft.bat (or convert it to .sh run on linux)

What is the expected output? What do you see instead?

queue creation seems to have failed
kernel is null!
kernel creation seems to have failed
Exception in thread "main" java.lang.IllegalStateException: kernel is null
        at com.amd.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:392)
        at com.amd.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:311)
        at com.amd.aparapi.sample.extension.FFTExample.main(FFTExample.java:102)

What version of the product are you using? On what operating system?

trunk

Please provide any additional information below.

The fft.cl file is not included in the JAR. Changes needed to  
samples/extension/build.xml




```

Original issue reported on code.google.com by `tOg...@gmail.com` on 16 Sep 2014 at 6:17

Attachments:
- [build.xml](https://storage.googleapis.com/google-code-attachments/aparapi/issue-153/comment-0/build.xml)
- [fft.sh](https://storage.googleapis.com/google-code-attachments/aparapi/issue-153/comment-0/fft.sh)

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the bug fix submission.

This has been fixed on the Aparapi GitHub site: 
https://github.com/aparapi/aparapi

Commit: 4fde95abb6164d41706b6fa65af63ac5dad69469 [4fde95a]
```

Original comment by `ryan.lam...@gmail.com` on 27 Sep 2014 at 9:01
- Changed state: **Fixed**
